In [1]:
import numpy as np

## Array Creation

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [11]:
#2D np array
b = np.array([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0],[1.0, 2.0, 3.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]]


In [12]:
#get dimension
b.ndim

2

In [13]:
#get shape
a.shape

(3,)

In [14]:
b.shape

(3, 3)

In [15]:
#get type
a.dtype

dtype('int32')

In [33]:
b.dtype

dtype('float64')

## Indexing

In [17]:
#indexing a[r,c]
b[1,1] #first row and first column element in array 'b' is 5.0

5.0

In [18]:
#negative indexing
b[1, -2] 

5.0

In [19]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]]


In [22]:
#get specific row(second)
b[1,:]

array([4., 5., 6.])

In [23]:
#get specific column(second)
b[:,1]

array([2., 5., 2.])

In [24]:
c= np.array([[1,2,3,4,5,6,7], [7,6,5,4,3,2,1]])
print(c)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


In [29]:
#[row, column, step]
c[1, 1:6: 2]

array([6, 4, 2])

In [31]:
#3D array
d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(d)     

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
#get number 4 from array
d[0,1,1]

4

In [36]:
#replace
d[:,1,:] = [[9,9],[8,8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing different types of arrays

In [39]:
#All 0's matrix
np.zeros(5, dtype = 'int32')

array([0, 0, 0, 0, 0])

In [46]:
np.ones([2,2,2], dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])